force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Employee Details</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Skill_Set__c.field-meta.xml
<CustomField>
    <fullName>Skill_Set__c</fullName>
    <label>Skill Set</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>C#.Net</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>Tableau</fullName>
            </value>
            <value>
                <fullName>Sample1</fullName>
            </value>
            <value>
                <fullName>Sample2</fullName>
            </value>
            <value>
                <fullName>Sample3</fullName>
            </value>
            <value>
                <fullName>Sample4</fullName>
            </value>
            <value>
                <fullName>Sample5</fullName>
            </value>
            <value>
                <fullName>Sample6</fullName>
            </value>
            <value>
                <fullName>Sample7</fullName>
            </value>
            <value>
                <fullName>Sample8</fullName>
            </value>
            <value>
                <fullName>Sample9</fullName>
            </value>
            <value>
                <fullName>Sample10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestClass.cls
public class TestClass {
    @AuraEnabled
    public static Contact[] method1(){
        return [Select name from contact];
    }
    @AuraEnabled
    public static List<String> getSkillSet()
    {
        List<String> options = new List<String>();
        
        Schema.DescribeFieldResult fieldResult =Employee__c.Skill_Set__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry f : ple)
        {
            options.add(f.getValue());
        }       
        return options;
    }
}